package br.com.pi.app;

import br.com.pi.bll.EnderecoBll;
import br.com.pi.bll.PessoaBll;
import br.com.pi.bll.PessoaPFBll;
import br.com.pi.bll.PessoaPJBll;
import br.com.pi.dal.PessoaPFDal;
import br.com.pi.design_patterns.template.OrdenaNome;
import br.com.pi.design_patterns.template.OrdenaEmail;
import br.com.pi.design_patterns.template.OrdenaTelefone;
import br.com.pi.design_patterns.template.PessoaOrdena;
import br.com.pi.model.EnderecoModel;
import br.com.pi.model.PessoaModel;
import br.com.pi.model.PessoaPFModel;
import br.com.pi.model.PessoaPJModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ClienteView extends javax.swing.JFrame {

    EnderecoBll enderecoBll;
    PessoaPFBll pessoaPFBll;
    PessoaPJBll pessoaPJBll;
    PessoaBll pessoaBll;
    EnderecoModel endereco;
    PessoaPFModel pessoaPFModel;
    PessoaPJModel pessoaPJModel;
    PessoaModel pessoamodel;
    String nomeUsuarioLogado;
    int idg;
    int idPessoa;

    boolean incluirEndereco = true;
    int idDeleteCliente;

    public ClienteView() throws Exception {

        initComponents();
        atualizarGrid();
        jComboBoxTipoPessoaActionPerformed(null);
        btnClientesSalvar.setEnabled(true);

        enderecoBll = new EnderecoBll();
        pessoaPFBll = new PessoaPFBll();
        pessoaPJBll = new PessoaPJBll();
        pessoaBll = new PessoaBll();

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/rental_car_key.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClienteDeletar = new javax.swing.JButton();
        btnClienteIncluir = new javax.swing.JButton();
        btnClienteCancelar = new javax.swing.JButton();
        btnClienteVoltar = new javax.swing.JButton();
        btnClientesSalvar = new javax.swing.JButton();
        btnClienteAlterar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCpfPessoa = new javax.swing.JFormattedTextField();
        txtNomePessoa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRgPessoa = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JFormattedTextField();
        jComboBoxTipoPessoa = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabViewClientes = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtClientesRua = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtClientesBairro = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtClientesCep = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtClientesComplemento = new javax.swing.JFormattedTextField();
        jComboxEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtClientesNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUsuarios2 = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestão de Clientes"));

        btnClienteDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/lixo-24.png"))); // NOI18N
        btnClienteDeletar.setText("Deletar");
        btnClienteDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteDeletar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClienteDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteDeletarActionPerformed(evt);
            }
        });

        btnClienteIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/mais.png"))); // NOI18N
        btnClienteIncluir.setText("Incluir");
        btnClienteIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteIncluir.setFocusPainted(false);
        btnClienteIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteIncluir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClienteIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteIncluirActionPerformed(evt);
            }
        });

        btnClienteCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/cancel_77947.png"))); // NOI18N
        btnClienteCancelar.setText("Cancelar");
        btnClienteCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteCancelar.setVerifyInputWhenFocusTarget(false);
        btnClienteCancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClienteCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCancelarActionPerformed(evt);
            }
        });

        btnClienteVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/voltar.png"))); // NOI18N
        btnClienteVoltar.setText("Voltar");
        btnClienteVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteVoltar.setIconTextGap(12);
        btnClienteVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteVoltarActionPerformed(evt);
            }
        });

        btnClientesSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/salve-24.png"))); // NOI18N
        btnClientesSalvar.setText("Salvar");
        btnClientesSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientesSalvar.setEnabled(false);
        btnClientesSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientesSalvar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClientesSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientesSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesSalvarActionPerformed(evt);
            }
        });

        btnClienteAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/icons/papel.png"))); // NOI18N
        btnClienteAlterar.setText("Alterar");
        btnClienteAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteAlterar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClienteAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClienteIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientesSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClienteCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteVoltar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClienteVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClienteIncluir)
                            .addComponent(btnClienteDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClientesSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClienteAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnClienteCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados dos Clientes"));

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        try {
            txtCpfPessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfPessoaKeyTyped(evt);
            }
        });

        jLabel3.setText("CNPJ");

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCnpjKeyTyped(evt);
            }
        });

        jLabel4.setText("RG");

        txtRgPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRgPessoaKeyTyped(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefone");

        jLabel6.setText("E-mail");

        jComboBoxTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Fisica", "Pessoa Juridica" }));
        jComboBoxTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPessoaActionPerformed(evt);
            }
        });

        jLabel14.setText("Nome Fantasia");

        jLabel15.setText("Razão Social");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomePessoa)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCpfPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeFantasia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCpfPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtRgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        tabViewClientes.setAutoCreateRowSorter(true);
        tabViewClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nome", "Email"
            }
        ));
        tabViewClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabViewClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabViewClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel7.setText("Rua");

        jLabel16.setText("Cidade *");

        jLabel17.setText("Bairro");

        jLabel18.setText("CEP");

        try {
            txtClientesCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtClientesCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClientesCepKeyTyped(evt);
            }
        });

        jLabel19.setText("Complemento");

        jComboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione UF>", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel8.setText("Número *");

        txtClientesNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClientesNumeroKeyTyped(evt);
            }
        });

        jLabel9.setText("ID");

        txtId.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(17, 17, 17)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientesBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txtClientesCep, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientesRua, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientesNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientesComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtClientesCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClientesBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel9)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtClientesRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtClientesNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtClientesComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Locações"));

        jTableUsuarios2.setAutoCreateRowSorter(true);
        jTableUsuarios2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nome", "Telefone", "E-mail"
            }
        ));
        jScrollPane3.setViewportView(jTableUsuarios2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Por", "Nome", "Telefone", "Email" }));
        jComboBoxPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPesquisa, 0, 378, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(629, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(202, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Hitorico de Clientes", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void limparEndereco() {
        txtCidade.setText("");
        txtClientesBairro.setText("");
        txtClientesCep.setText("");
        txtClientesRua.setText("");
        txtClientesComplemento.setText("");
        txtClientesNumero.setText("");
        jComboxEstado.setSelectedItem("<Selecione UF>");
        txtId.setText("");
    }

    private void btnClienteVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteVoltarActionPerformed
        try {
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            menu.transferirDados(nomeUsuarioLogado);
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnClienteVoltarActionPerformed
    /**
     * Botão incluir um novo dado no banco de dados e ativa o botão SALVAR
     *
     * @param evt
     */
    private void btnClienteIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteIncluirActionPerformed


    }//GEN-LAST:event_btnClienteIncluirActionPerformed

    private void btnClientesSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesSalvarActionPerformed
        try {
            validaCampo();
            pessoamodel = new PessoaModel();
            pessoaPFModel = new PessoaPFModel();
            pessoaPJModel = new PessoaPJModel();
            endereco = new EnderecoModel();
            if (jComboBoxTipoPessoa.getSelectedItem().toString().equalsIgnoreCase("Pessoa Fisica")) {
                //Pegando dados de endereço
                endereco.setEndereco_cep(txtClientesCep.getText());
                endereco.setEndereco_cidade(txtCidade.getText());
                endereco.setEndereco_bairro(txtClientesBairro.getText());
                endereco.setEndereco_rua(txtClientesRua.getText());
                endereco.setEndereco_numero(Integer.parseInt(txtClientesNumero.getText()));
                endereco.setEndereco_estado(jComboxEstado.getSelectedItem().toString());
                endereco.setEndereco_complemento(txtClientesComplemento.getText());
                //Pegando dados de Pessoa
                pessoaPFModel.setPessoa_nome(txtNomePessoa.getText());
                pessoaPFModel.setPessoa_email(txtEmail.getText());
                pessoaPFModel.setPessoa_telefone(txtTelefone.getText());
                pessoaPFModel.setPessoa_endereco(endereco);
                //Pegando dados de pessoaPF
                pessoaPFModel.setPessoa_pf_cpf(txtCpfPessoa.getText());
                pessoaPFModel.setPessoa_pf_rg(txtRgPessoa.getText());
                pessoaPFModel.setPessoa(pessoaPFModel);
                pessoaPFBll.addAll(endereco, pessoaPFModel);

                limparCampos();
                atualizarGrid();
            } else {
                //Pegando dados de endereço
                endereco.setEndereco_cep(txtClientesCep.getText());
                endereco.setEndereco_cidade(txtCidade.getText());
                endereco.setEndereco_bairro(txtClientesBairro.getText());
                endereco.setEndereco_rua(txtClientesRua.getText());
                endereco.setEndereco_numero(Integer.parseInt(txtClientesNumero.getText()));
                endereco.setEndereco_estado(jComboxEstado.getSelectedItem().toString());
                endereco.setEndereco_complemento(txtClientesComplemento.getText());
                //Pegando dados de Pessoa
                pessoaPJModel.setPessoa_nome(txtNomePessoa.getText());
                pessoaPJModel.setPessoa_email(txtEmail.getText());
                pessoaPJModel.setPessoa_telefone(txtTelefone.getText());
                pessoaPJModel.setPessoa_endereco(endereco);
                //Pegando dados de pessoaPJ
                pessoaPJModel.setPessoa_pj_nomeFantasia(txtNomeFantasia.getText());
                pessoaPJModel.setPessoa_pj_razaoSocial(txtRazaoSocial.getText());
                pessoaPJModel.setPessoa_pj_cnpj(txtCnpj.getText());
                pessoaPJModel.setPessoaModel(pessoaPJModel);
                pessoaPJBll.addAll(endereco, pessoaPJModel);

                limparCampos();
                atualizarGrid();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_btnClientesSalvarActionPerformed

    private void jComboBoxTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessoaActionPerformed
        if (jComboBoxTipoPessoa.getSelectedItem().toString().contains("Pessoa Fisica")) {
            txtNomeFantasia.setEnabled(false);
            txtRazaoSocial.setEnabled(false);
            txtCnpj.setEnabled(false);
            txtCpfPessoa.setEnabled(true);
            txtRgPessoa.setEnabled(true);
            txtCpfPessoa.setEnabled(true);
        } else {
            txtCpfPessoa.setEnabled(false);
            txtRgPessoa.setEnabled(false);
            txtCpfPessoa.setEnabled(false);
            txtNomeFantasia.setEnabled(true);
            txtRazaoSocial.setEnabled(true);
            txtCnpj.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxTipoPessoaActionPerformed

    private void limparCampos() {
        txtNomePessoa.setText("");
        txtEmail.setText("");
        txtClientesBairro.setText("");
        txtClientesCep.setText("");
        txtCidade.setText("");
        txtClientesNumero.setText("");
        txtClientesRua.setText("");
        txtId.setText("");
        txtClientesComplemento.setText("");
        txtRgPessoa.setText("");
        txtCpfPessoa.setText("");
        txtCnpj.setText("");
        txtNomeFantasia.setText("");
        txtRazaoSocial.setText("");
        txtTelefone.setText("");

    }

    private void validaCampo() throws Exception {
        if (txtClientesNumero.getText().isEmpty() == true) {
            throw new Exception("Preencha o campo de numero");
        }
    }

    private void tabViewClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabViewClientesMouseClicked
        idg = Integer.parseInt(tabViewClientes.getValueAt(tabViewClientes.getSelectedRow(), 0).toString());

        pessoaPFModel = new PessoaPFModel();
        pessoaPJModel = new PessoaPJModel();

        limparCampos();

        try {

            //Setando pessoa
            pessoamodel = (PessoaModel) pessoaBll.getById(idg);
            txtNomePessoa.setText(pessoamodel.getPessoa_nome());
            txtEmail.setText(pessoamodel.getPessoa_email());
            txtTelefone.setText(pessoamodel.getPessoa_telefone());
            //Sentando Endereço
            txtClientesBairro.setText(pessoamodel.getPessoa_endereco().getEndereco_bairro());
            txtClientesCep.setText(pessoamodel.getPessoa_endereco().getEndereco_cep());
            txtCidade.setText(pessoamodel.getPessoa_endereco().getEndereco_cidade());
            txtClientesNumero.setText(pessoamodel.getPessoa_endereco().getEndereco_numero() + "");
            txtClientesRua.setText(pessoamodel.getPessoa_endereco().getEndereco_rua());
            txtId.setText(pessoamodel.getPessoa_endereco().getEndereco_iden() + "");
            txtClientesComplemento.setText(pessoamodel.getPessoa_endereco().getEndereco_complemento());

            pessoaPFModel.setPessoa_pf_cpf(null);
            pessoaPJModel.setPessoa_pj_cnpj(null);

            pessoaPFModel = (PessoaPFModel) pessoaPFBll.getById(idg);

            if (pessoaPFModel.getPessoa_pf_cpf() != null) {
                idPessoa = pessoaPFModel.getPessoa_idem();
                txtRgPessoa.setText(pessoaPFModel.getPessoa_pf_rg());
                txtCpfPessoa.setText(pessoaPFModel.getPessoa_pf_cpf());
                jComboBoxTipoPessoa.setSelectedItem("Pessoa Fisica");

            } else {
                pessoaPJModel = (PessoaPJModel) pessoaPJBll.getById(idg);
                idPessoa = pessoaPJModel.getPessoa_idem();
                txtCnpj.setText(pessoaPJModel.getPessoa_pj_cnpj());
                txtNomeFantasia.setText(pessoaPJModel.getPessoa_pj_nomeFantasia());
                txtRazaoSocial.setText(pessoaPJModel.getPessoa_pj_razaoSocial());
                jComboBoxTipoPessoa.setSelectedItem("Pessoa Juridica");

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());

        }
    }//GEN-LAST:event_tabViewClientesMouseClicked
    private void btnClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAlterarActionPerformed
        try {
            validaCampo();
            pessoamodel = new PessoaModel();
            pessoaPFModel = new PessoaPFModel();
            pessoaPJModel = new PessoaPJModel();
            endereco = new EnderecoModel();
            if (jComboBoxTipoPessoa.getSelectedItem().toString().equalsIgnoreCase("Pessoa Fisica")) {
                //Pegando dados de endereço
                endereco.setEndereco_cep(txtClientesCep.getText());
                endereco.setEndereco_cidade(txtCidade.getText());
                endereco.setEndereco_bairro(txtClientesBairro.getText());
                endereco.setEndereco_rua(txtClientesRua.getText());
                endereco.setEndereco_numero(Integer.parseInt(txtClientesNumero.getText()));
                endereco.setEndereco_estado(jComboxEstado.getSelectedItem().toString());
                endereco.setEndereco_complemento(txtClientesComplemento.getText());
                endereco.setEndereco_iden(Integer.parseInt(txtId.getText()));
                //Pegando dados de Pessoa
                pessoamodel.setPessoa_idem(idg);
                pessoamodel.setPessoa_nome(txtNomePessoa.getText());
                pessoamodel.setPessoa_email(txtEmail.getText());
                pessoamodel.setPessoa_telefone(txtTelefone.getText());
                pessoamodel.setPessoa_endereco(endereco);

                //Pegando dados de pessoaPF
                pessoaPFModel.setPessoa_pf_cpf(txtCpfPessoa.getText());
                pessoaPFModel.setPessoa_pf_rg(txtRgPessoa.getText());
                pessoaPFModel.setPessoa_pf_idem(idPessoa);
                pessoaPFModel.setPessoa(pessoamodel);
                pessoaPFBll.updateAll(endereco, pessoamodel, pessoaPFModel);

                limparCampos();
                atualizarGrid();
            } else {
                endereco.setEndereco_cep(txtClientesCep.getText());
                endereco.setEndereco_cidade(txtCidade.getText());
                endereco.setEndereco_bairro(txtClientesBairro.getText());
                endereco.setEndereco_rua(txtClientesRua.getText());
                endereco.setEndereco_numero(Integer.parseInt(txtClientesNumero.getText()));
                endereco.setEndereco_estado(jComboxEstado.getSelectedItem().toString());
                endereco.setEndereco_complemento(txtClientesComplemento.getText());
                endereco.setEndereco_iden(Integer.parseInt(txtId.getText()));
                //Pegando dados de Pessoa
                pessoamodel.setPessoa_idem(idg);
                pessoamodel.setPessoa_nome(txtNomePessoa.getText());
                pessoamodel.setPessoa_email(txtEmail.getText());
                pessoamodel.setPessoa_telefone(txtTelefone.getText());
                pessoamodel.setPessoa_endereco(endereco);
                //Pegando dados de pessoaPJ
                pessoaPJModel.setPessoa_pj_nomeFantasia(txtNomeFantasia.getText());
                pessoaPJModel.setPessoa_pj_razaoSocial(txtRazaoSocial.getText());
                pessoaPJModel.setPessoa_pj_cnpj(txtCnpj.getText());
                pessoaPJModel.setPessoaModel(pessoamodel);
                pessoaPJModel.setPessoa_pj_idem(idPessoa);

                pessoaPJBll.updateAll(endereco, pessoamodel, pessoaPJModel);

                limparCampos();
                atualizarGrid();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());

        }
    }//GEN-LAST:event_btnClienteAlterarActionPerformed

    private void btnClienteDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteDeletarActionPerformed
        try {
            if (jComboBoxTipoPessoa.getSelectedItem().toString().equalsIgnoreCase("Pessoa Fisica")) {
                pessoaPFBll.deleteAll(Integer.parseInt(txtId.getText()), idg, idg);
                limparCampos();
                atualizarGrid();
            } else {
                pessoaPJBll.deleteAll(Integer.parseInt(txtId.getText()), idg, idg);
                limparCampos();
                atualizarGrid();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnClienteDeletarActionPerformed

    private void txtCpfPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfPessoaKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCpfPessoaKeyTyped

    private void txtRgPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgPessoaKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRgPessoaKeyTyped

    private void txtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }    }//GEN-LAST:event_txtTelefoneKeyTyped

    private void txtCnpjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }    }//GEN-LAST:event_txtCnpjKeyTyped

    private void txtClientesNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientesNumeroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtClientesNumeroKeyTyped

    private void txtClientesCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientesCepKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")
                && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }    }//GEN-LAST:event_txtClientesCepKeyTyped

    private void btnClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCancelarActionPerformed
        try {

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnClienteCancelarActionPerformed

    private void jComboBoxPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaActionPerformed
        OrdenaNome nome;
        OrdenaEmail email;
        OrdenaTelefone telefone;

        try {
            if (jComboBoxPesquisa.getSelectedItem().toString().contains("Nome")) {
                nome = new OrdenaNome();
                imprimirNaGrid(nome.getAllPesquisa());

            }
            if (jComboBoxPesquisa.getSelectedItem().toString().contains("Email")) {
                email = new OrdenaEmail();
                imprimirNaGrid(email.getAllPesquisa());

            }
            if (jComboBoxPesquisa.getSelectedItem().toString().contains("Telefone")) {
                telefone = new OrdenaTelefone();
                imprimirNaGrid(telefone.getAllPesquisa());

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jComboBoxPesquisaActionPerformed

    private void atualizarGrid() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tabViewClientes.getModel();
        model.setRowCount(0);
        Object[] linha;
        pessoaBll = new PessoaBll();
        Iterator<PessoaModel> listaDeUsuario = pessoaBll.getAll();
        for (Iterator<PessoaModel> it = listaDeUsuario; it.hasNext();) {
            PessoaModel aux = it.next();
            linha = new Object[]{
                aux.getPessoa_idem(),
                aux.getPessoa_nome(),
                aux.getPessoa_email(),};
            model.addRow(linha);

        }
    }

    private void imprimirNaGrid(ArrayList<PessoaModel> dados) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableUsuarios2.getModel();
            model.setNumRows(0);
            int pos = 1;
            while (pos < dados.size()) {
                String[] linha = new String[4];
                PessoaModel obj = dados.get(pos);
                linha[0] = obj.getPessoa_idem() + "";
                linha[1] = obj.getPessoa_nome();
                linha[2] = obj.getPessoa_telefone();
                linha[3] = obj.getPessoa_email();
                model.addRow(linha);
                pos++;
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClienteView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAlterar;
    private javax.swing.JButton btnClienteCancelar;
    private javax.swing.JButton btnClienteDeletar;
    private javax.swing.JButton btnClienteIncluir;
    private javax.swing.JButton btnClienteVoltar;
    private javax.swing.JButton btnClientesSalvar;
    private javax.swing.JComboBox<String> jComboBoxPesquisa;
    private javax.swing.JComboBox<String> jComboBoxTipoPessoa;
    private javax.swing.JComboBox<String> jComboxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableUsuarios2;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTable tabViewClientes;
    private javax.swing.JFormattedTextField txtCidade;
    private javax.swing.JFormattedTextField txtClientesBairro;
    private javax.swing.JFormattedTextField txtClientesCep;
    private javax.swing.JFormattedTextField txtClientesComplemento;
    private javax.swing.JTextField txtClientesNumero;
    private javax.swing.JFormattedTextField txtClientesRua;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtCpfPessoa;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtNomeFantasia;
    private javax.swing.JFormattedTextField txtNomePessoa;
    private javax.swing.JFormattedTextField txtRazaoSocial;
    private javax.swing.JFormattedTextField txtRgPessoa;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

}
